#!/bin/bash

HERE="$(dirname "$(readlink -f "${0}")")"

progName="notepad-plus-plus"
progArch="-x86_64"
progVer=
progRealPath="$HERE/usr/share/$progName"
progHome="$HOME/.$progName"
progBin="notepad++.exe"
progIcoD="$HOME/.local/share/applications/$progName.desktop"
progReg="/tmp/dlloverrides.reg"

# Symlink stuff
mkdir -p "$progHome" || exit 1
# Delete broken symlinks
find -L "$progHome" -maxdepth 2 -type l -delete
# Update existing symlinks, add new symlinks
cp -urs "$progRealPath/"* "$progHome" 2> /dev/null

dkico() {
if [[ ! -f $progIcoD ]]; then

cp -r "$HERE"/usr/share/icons "${HOME}"/.local/share
mkdir -p "${HOME}/.local/share/applications"
DesktopFilePath="${HOME}/.local/share/applications/$progName.desktop"

{
echo "[Desktop Entry]"
echo "Type=Application"
echo "Name=Notepad++"
echo "GenericName=Text Editor"
echo "Comment=Simple and free source code editor."
echo "Encoding=UTF-8"
echo "Version=$progVer"
echo "Icon=$progName"
echo "TryExec=${OWD}/${progName}_${progVer}${progArch}.AppImage"
echo "Exec=${OWD}/${progName}_${progVer}${progArch}.AppImage %F"
echo "MimeType=text/plain;text/css;text/html;text/x-c++hdr;text/x-c++src;text/x-chdr;text/x-java;text/x-makefile;text/x-python;text/x-sh;application/x-wine-extension-ini;application/x-wine-extension-inf;"
echo "Categories=Utility;TextEditor;"
echo "Terminal=false"
echo "StartupWMClass=$progBin"
} >> "$DesktopFilePath"

fi
}

# check for wine appimage
wine_file=$(find "$HOME"/Downloads "$HOME"/bin "$HOME"/.local/bin -type f \( -name '*.appimage' -o -name '*.AppImage' \) 2>/dev/null | grep -e "wine-stable" -e 'Wine-stable' | head -n 1)

if [[ -f $wine_file ]]; then

# Calling binary files from other AppImage having $ARGV0

export winecmd=$wine_file

function wine {
  $winecmd wine "$@"
}

function wineserver {
  $winecmd wineserver "$@"
}

function winetricks {
  $winecmd winetricks -q "$@"
}

else
echo "wine-stable appimage is missing can not run npp"
echo ""
echo "Download wine-stable*.appimage from https://github.com/mmtrt/WINE_Appimage/releases"
echo ""
echo "Then"
echo ""
echo "chmod +x wine-stable*.AppImage"
echo ""
echo "Also make sure you have single copy of wine-stable appimage present these locations"
echo ""
echo "$HOME/Downloads ; $HOME/bin ; $HOME/.local/bin"
exit 1
fi

# Create custom $WINEPREFIX and add $WINEDLLOVERRIDES
export WINEPREFIX="${progHome}/.wine" WINEDLLOVERRIDES="mscoree,mshtml=" WINEDEBUG=fixme-all

if [[ ! -d $WINEPREFIX ]]; then

# link ttf & ttc fonts from root to wineprefix
mkdir -p "$WINEPREFIX"/drive_c/windows/Fonts
find /usr/share/fonts/ -type f \( -name "*.ttf" -o -name "*.ttc" \) -exec ln -vs "{}" "$WINEPREFIX"/drive_c/windows/Fonts/ \; &>/dev/null

mkdir -p "$WINEPREFIX"/drive_c/users/"$USER"
cp -R "$HERE/winedata/Application Data" "$WINEPREFIX"/drive_c/users/"$USER"

# Remove xml file links & copy xml files
rm "$progHome"/updater/gup.xml &>/dev/null
cp "$progRealPath"/updater/gup.xml "$progHome"/updater &>/dev/null

for xmls in $(ls $progRealPath/ | grep xml); do
    rm $progHome/$xmls &>/dev/null
    cp $progRealPath/$xmls $progHome/ &>/dev/null
done

# Check for LANG=zh_* in locale and apply font changes if it exists.
if (locale | grep -e 'LANG=zh_CN' -e 'LANG=zh_SG') >/dev/null 2>&1; then cat > $progReg <<'EOF'
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\FontSubstitutes]
"MS Shell Dlg"="Noto Sans CJK SC"
"Tms Rmn"="Noto Sans CJK SC"
EOF
wine regedit $progReg
sleep 1
rm $progReg &>/dev/null
fi

if (locale | grep -e 'LANG=zh_HK' -e 'LANG=zh_MO' -e 'LANG=zh_TW') >/dev/null 2>&1; then cat > $progReg <<'EOF'
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\FontSubstitutes]
"MS Shell Dlg"="Noto Sans CJK TC"
"Tms Rmn"="Noto Sans CJK TC"
EOF
wine regedit $progReg
sleep 1
rm $progReg &>/dev/null
fi

fi

# Passing args to wine apps
for i; do # for i = for i in "$@"
    # Add path in Wine form (e.g. "z:/home/user/Desktop/lol.xyz")
    if [[ -f /${i#?:} ]]; then 
        args+=("z:${i#?:}")   # When opened through .desktop or Wine path (e.g. z:/*)
    elif [[ "${i:0:1}" = "-" ]]; then
        args+=("${i/#-//}")
    fi
done

# Launch wineboot/winecfg/winetricks if requested.
# If the executable exists then launch it.
case "$1" in
  "install")
    dkico
    ;;
  "winetricks")
    winetricks "$2" "$3"
    ;;
  "msiexec"|"notepad"|"regedit"|"regsvr32"|"wineboot"|"winecfg"|"wineconsole"|"winedbg"|"winefile"|"winemine"|"winepath")
    wine "$1"
    ;;
  "/playpause"|"/stop"|"/next"|"/prev"|"/random"|"/config")
    wine "$progHome/$progBin" "$1"
    ;;
  *)
    wine "$progHome/$progBin" "${args[@]}" 2>/dev/null
    ;;
esac
