# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
#   Build at 00:00 on every 15th day-of-month.
#   schedule:
#     - cron: "0 0 */15 * *"
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "npp"
  npp:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Set NPP_VER
      - name: Run version script
        run: echo "NPP_VER=$(wget 2>/dev/null https://api.github.com/repos/notepad-plus-plus/notepad-plus-plus/releases -qO - 2>&1 | grep "Notepad++ " | sed s'|"| |g' | awk '{print $5}' | head -n1)" >> $GITHUB_ENV

      # Runs a set of commands using the runners shell
      - name: Run a single-line script
        run: |
          sudo apt update && sudo apt install libfuse2 -y
          bash deploy.sh stable

      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: notepad-plus-plus-continuous-x86_64.AppImage
          path: 'dist'

  # This workflow contains a single job called "npp-box86"
  npp-box86:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Set NPP_VER
      - name: Run version script
        run: echo "NPP_VER=$(wget 2>/dev/null https://api.github.com/repos/notepad-plus-plus/notepad-plus-plus/releases -qO - 2>&1 | grep "Notepad++ " | sed s'|"| |g' | awk '{print $5}' | head -n1)" >> $GITHUB_ENV

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          sudo apt update && sudo apt install libfuse2 -y
          bash deploy.sh stable-box86

      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: notepad-plus-plus-continuous-aarch64.AppImage
          path: 'dist'

  # This workflow contains a single job called "npp-wp"
  npp-wp:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Set NPP_VER
      - name: Run version script
        run: echo "NPP_VER=$(wget 2>/dev/null https://api.github.com/repos/notepad-plus-plus/notepad-plus-plus/releases -qO - 2>&1 | grep "Notepad++ " | sed s'|"| |g' | awk '{print $5}' | head -n1)_WP" >> $GITHUB_ENV

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          sudo dpkg --add-architecture i386 && sudo apt update && sudo apt install libfuse2 libfuse2:i386 libglu1-mesa:i386
          xvfb-run --server-args="-screen 0 1024x768x24" bash deploy.sh stablewp

      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: notepad-plus-plus-continuous-wp-x86_64.AppImage
          path: 'dist'

  release-stable:
    needs: [npp]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v1
        with:
          name: notepad-plus-plus-continuous-x86_64.AppImage

      - name: release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: notepad-plus-plus stable
          automatic_release_tag: stable
          prerelease: false
          draft: false
          files: |
            notepad-plus-plus-continuous-x86_64.AppImage
          repo_token: ${{ secrets.GITHUB_TOKEN }}

  release-stable-wp:
    needs: [npp-wp]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v1
        with:
          name: notepad-plus-plus-continuous-wp-x86_64.AppImage

      - name: release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: notepad-plus-plus stable with wineprefix
          automatic_release_tag: stable-wp
          prerelease: false
          draft: false
          files: |
            notepad-plus-plus-continuous-wp-x86_64.AppImage
          repo_token: ${{ secrets.GITHUB_TOKEN }}

  release-stable-box86:
    needs: [npp-box86]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v1
        with:
          name: notepad-plus-plus-continuous-aarch64.AppImage

      - name: release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: notepad-plus-plus stable box86
          automatic_release_tag: stable-box86
          prerelease: false
          draft: false
          files: |
            notepad-plus-plus-continuous-aarch64.AppImage
          repo_token: ${{ secrets.GITHUB_TOKEN }}